add phase banner test and functionality
govuk-one-login/di-fec-ga4 pull request #22
Opened 2023-12-07 14:29 UTC by Joanneyoung01

### Description ###
Adds logic to set the phase banner links on navigation change

### Tickets ###
(DFC-129)[https://govukverify.atlassian.net/browse/DFC-129]

### Steps to Reproduce ###
- Click on the phase banner links
- Validate this on local + gtm

![Screenshot 2023-12-07 at 14 24 17](https://github.com/govuk-one-login/di-fec-ga4/assets/38694448/c4b0a44e-12e7-48e1-9755-36770935c83e)
![Screenshot 2023-12-07 at 14 26 38](https://github.com/govuk-one-login/di-fec-ga4/assets/38694448/5731c127-6414-42e4-9899-33f68a58caae)

2023-12-07 14:58 UTC, di-fabs requested changes

2023-12-07 14:58 UTC, di-fabs commented on src/analytics/navigationTracker/navigationTracker.ts
> +  isPhaseBannerLink(element: HTMLElement): boolean {
Well Done!
This function will be very useful later, when we will have to deal with the section property.

2023-12-07 14:58 UTC, di-fabs commented on src/analytics/navigationTracker/navigationTracker.ts
> +        return "phase banner";
Following the latest doc we have, the type needs to be "header menu bar" when the visitor clicks on the phase banner.
Only the section property (which we will not managing for the moment) needs to take the value "phase banner"
more info: https://govukverify.atlassian.net/browse/DFC-149 (section Header Bar Navigation)
But your condition is good. Just need to be associated to the "if" which return the value "header menu bar"

2023-12-07 14:58 UTC, di-fabs commented on src/analytics/navigationTracker/navigationTracker.ts
> +    return footer && footer.contains(element);
Well spotted!

2023-12-07 16:00 UTC, Joanneyoung01 commented on src/analytics/navigationTracker/navigationTracker.ts
> +      } else if (this.isPhaseBannerLink(element)) {
Oh yes of course 🙈 don't know how i didn't spot that haha thank you! 🤦

2023-12-07 16:02 UTC, di-fabs approved these changes

2023-12-08 12:38 UTC, di-aholme approved these changes

2023-12-08 14:35 UTC, closed without merging