DFC-392 add docs and remove console log
govuk-one-login/di-fec-ga4 pull request #51
Opened 2024-02-27 09:14 UTC by di-fabs

Add docs about trackers

2024-02-27 12:57 UTC, SophiaWokoma requested changes
looks good to me , just spotted a few typos :)

2024-02-27 12:57 UTC, SophiaWokoma commented on docs/analytics.md
> +- active the Form Response Tracker
activate**

2024-02-27 12:57 UTC, SophiaWokoma commented on docs/analytics.md
> +object) in the same base nunjucks template which initialises analytics and the cookie banner. We pass the `containerId`s and `disableGa4Tracking` as paramters, `disableGa4Tracking`, `disableUaTrackin
parameters**

2024-02-27 12:57 UTC, SophiaWokoma commented on docs/analytics.md
> +these values can be inject by your `setLocal` middleware functions which grabs these values from the current environment.
injected**

2024-02-27 12:57 UTC, SophiaWokoma commented on docs/formTrackers.md
> +`form_error` event is pushed when the user loads a form which contains form error message.
contains a **

2024-02-27 12:57 UTC, SophiaWokoma commented on docs/formTrackers.md
> +`form_change` event is pushed when the user loads a form because he/she wants to change the answer.
they want to**

2024-02-27 12:57 UTC, SophiaWokoma commented on docs/pageViewTracker.md
> +#### first_publish_at
first_published_at **

2024-02-27 13:11 UTC, Joanneyoung01 commented on docs/analytics.md
> +The `analytics.js` file has to be include in the base nunjucks template (e.g: `src/views/common/layout/base.njk`) as a script,
*included

2024-02-27 19:17 UTC, SophiaDWokoma requested changes

2024-02-27 19:17 UTC, SophiaDWokoma commented on docs/analytics.md
> +- active the Form Response Tracker
activate**

2024-02-27 19:17 UTC, SophiaDWokoma commented on docs/analytics.md
> +We then call our `appInit` (`src/index.ts`) function (which is now accessible on the global window
parameters**

2024-02-27 19:17 UTC, SophiaDWokoma commented on docs/analytics.md
> +these values can be inject by your `setLocal` middleware functions which grabs these values from the current environment.
injected**

2024-02-27 19:17 UTC, SophiaDWokoma commented on docs/formTrackers.md
> +`form_error` event is pushed when the user loads a form which contains form error message.
contains a form error message/(s)**

2024-02-27 19:17 UTC, SophiaDWokoma commented on docs/formTrackers.md
> +`form_change` event is pushed when the user loads a form because he/she wants to change the answer.
they want to ***

2024-02-27 19:17 UTC, SophiaDWokoma commented on docs/pageViewTracker.md
> +#### first_publish_at
first_published_at **

2024-02-28 09:30 UTC, Joanneyoung01 approved these changes

2024-02-28 09:55 UTC, SophiaDWokoma approved these changes

2024-02-28 09:57 UTC, merged